modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="rpgskills"
version="1.0.0"
displayName="RPGskills"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rereskillable"
credits="Skillable, Reskillable and Rereskillable"
authors="sodalish"
description='''
RPGskills is a rewrite of Reskillable/Rereskillable for Minecraft Forge 1.16.5. Skills include: Power, Defense, Mining, Cooking, Farming, Crafting, Focus and Magic
'''

[[dependencies.rpgskills]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rpgskills]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rpgskills]]
    modId="curios"
    mandatory=false
    versionRange="[1.16.5-4.0.5.0,)"
    ordering="AFTER"
    side="BOTH"